# DLEM dev image
FROM dlem-build

RUN groupadd --system --gid 999 nonroot \
 && useradd --system --gid 999 --uid 999 --create-home nonroot

ENV UV_NO_DEV=0
RUN pixi install --environment dev && \
    pixi clean

ENTRYPOINT []

CMD []