services:
#Service to run dLEM with own data
  dlem:
    image: dlem
    container_name: dlem
    build:
      context: .
      dockerfile: Dockerfile_prod
    volumes:
      - ${IN_DATA_DIR}:/dlem/data/
    command: >
      dlem /dlem/data/${IN_DATA} /dlem/data/test_out
#Service to build dLEM image
  dlem-build:
    image: dlem-build
    container_name: dlem-build
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${REPO_DIR}/dist:/dlem/dist"
    user: root
#Service to develop dLEM
  dlem-dev:
    user: root
    image: dlem-dev
    container_name: dlem-dev
    build:
      context: .
      dockerfile: Dockerfile_dev
    command: ["tail", "-F", "/dev/null"]
    develop:
      watch:
        - action: sync
          path: .
          target: /dlem
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
#Service to run test for dLEM
  dlem-test:
    image: dlem-dev
    container_name: dlem-test
    user: root
    command: >
      pytest -k "test_dlem_synthetic"
