services:
#Service to run dLEM with own data
  dlem:
    image: dlem
    container_name: dlem
    build:
      context: .
      dockerfile: Dockerfile_prod
    depends_on:
      dlem-build:
        condition: service_completed_successfully
    volumes:
      - ${IN_DATA_DIR}:/dlem/data/
    command: --help
#Service to build dLEM image
  dlem-build:
    image: dlem-dev
    container_name: dlem-build
    command: pixi run build
    volumes:
      - "${REPO_DIR}/dist:/dlem/dist"
    user: root
#Service to develop dLEM
  dlem-dev:
    user: root
    image: dlem-dev
    container_name: dlem-dev
    build:
      context: .
      dockerfile: Dockerfile_dev
    depends_on:
      dlem-build:
        condition: service_completed_successfully
    command: ["tail", "-F", "/dev/null"]
    develop:
      watch:
        - action: sync
          path: .
          target: /dlem
          ignore:
            - .venv/
        - action: rebuild
          path: ./pixi.lock
#Service to run test for dLEM
  dlem-test:
    image: dlem-dev
    container_name: dlem-test
    user: root
    command: >
      pixi run --environment dev pytest -k "test_dlem_drem_small or test_dlem_drem_medium or test_dlem_synthetic"