# DLEM dev image
FROM debian:stable-slim

ENV APT_PACKAGES=" \
		ca-certificates \
		zlib1g \
		zlib1g-dev \
		curl \
        build-essential \
		"

#Set up shell for install
USER root
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash","-c"]
ENV BASH_EN=/${USER}/.bashrc
ENV SHELL=/bin/bash
ENV TZ="America/New_York"

# Set working directory
ARG WORKDIR="/dlem"
WORKDIR ${WORKDIR}

#Get apt packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends ${APT_PACKAGES} && \
    rm -rf "/var/lib/apt/lists/*" && \
    apt-get clean && \
    rm -rf /var/cache/apt && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

ENV PIXI_HOME="/opt/pixi"
ENV PATH=${PIXI_HOME}/bin:$PATH
COPY . /dlem
RUN curl -fsSL https://pixi.sh/install.sh | sh && \
	echo 'eval "$(pixi completion --shell bash)"' > ${BASH_EN} && \
	source ${BASH_EN} && \
    pixi install --environment dev && \
    pixi clean

ENTRYPOINT []

CMD []