FROM dlem-build AS builder

ENV UV_COMPILE_BYTECODE=1 
ENV UV_LINK_MODE=copy
ENV UV_NO_DEV=1
ENV UV_PYTHON_INSTALL_DIR=/python
ENV UV_PYTHON_PREFERENCE=only-managed

FROM debian:bookworm-slim

RUN groupadd --system --gid 999 nonroot \
 && useradd --system --gid 999 --uid 999 --create-home nonroot

COPY --from=builder --chown=python:python /python /python
COPY --from=builder --chown=nonroot:nonroot /dlem /dlem
ENV PATH="/dlem/.venv/bin:$PATH"

USER nonroot

WORKDIR /dlem

ENTRYPOINT ["dlem"]