[project]
name = "dlem-jax"
version = "0.1.0"
description = "Tool to build, train, and use the differentiable Loop Extrusion Model (dLEM)"
readme = "README.md"
requires-python = ">=3.11,<=3.14"
dependencies = [
    "cooler>=0.10.4",
    "cython>=3.2.1",
    "hictkpy[all]>=1.4.0",
    "jax>=0.9.0",
    "jaxlib>=0.6.2",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.0",
    "pybind11>=2.12",
    "optax>=0.2.6",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "pybigwig>=0.3.25",
    "pyranges1>=0.1.1",
    "pyrle>=0.0.42",
    "requests>=2.32.5",
    "rich>=13.0.0",
    "scipy>=1.17.0",
    "typer>=0.19.2",
    "numpy>=2.4.2",
]

[project.optional-dependencies]
cuda = ["jax[cuda12]>=0.9.0"]

[tool.uv.workspace]
members = [
    "",
]

[project.scripts]
dlem = "dlem.cli:dlem_cli"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["dlem*"]

[dependency-groups]
dev = [
    "ipykernel",
    "mkdocs>=1.6.1",
    "mkdocs-jupyter==0.25.0",
    "mkdocstrings[python]>=1.0.0",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "sh>=2.2.2", 
    "python-build>=0.2.13,<0.3", 
    "ruff>=0.14.13,<0.15",
]

[tool.pytest.ini_options]
testpaths = [ "tests"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[tool.pixi.pypi-dependencies]
dlem = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.feature.dev]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]

[tool.pixi.feature.dev.dependencies]
hictk = ">=2.2.0,<3"
uv = ">=0.9.26,<0.10"

[tool.pixi.feature.dev.tasks]
build = "uv build --sdist --wheel"

[tool.pixi.target.linux-64.pypi-dependencies]
jax = { version = ">=0.9.0, <0.10", extras = ["cuda12"] }
jax-cuda12-pjrt = ">=0.9.0, <0.10"
jax-cuda12-plugin = ">=0.9.0, <0.10"
