[project]
name = "dlem"
version = "0.1.0"
description = "Tool to build, train, and use the differentiable Loop Extrusion Model (dLEM)"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "cooler",
    "cython>=3.2.1",
    "hictkpy[all]>=1.4.0",
    "jax>=0.6.2 ; sys_platform == 'windows'",
    "jax-cuda12-pjrt ; sys_platform == 'linux'",
    "jax-cuda12-plugin>=0.6.2 ; sys_platform == 'linux'",
    "jax-metal>=0.1.1 ; sys_platform == 'darwin'",
    "jax[cuda12]>=0.6.2 ; sys_platform == 'linux'",
    "jaxlib>=0.6.2",
    "matplotlib>=3.10.7",
    "numpy",
    "optax>=0.2.6",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "pybigwig>=0.3.24",
    "pyranges>=0.1.4",
    "pyrle>=0.0.42",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "scipy",
    "typer>=0.19.2",
]

[tool.uv.workspace]
members = [
    "",
]

[project.scripts]
dlem = "dlem.cli:dlem_cli"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "dlem"
module-root = ""

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "mkdocs>=1.6.1",
    "mkdocs-jupyter>=0.24.1",
    "mkdocstrings[python]>=1.0.0",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "sh>=2.2.2",
]

[tool.pytest.ini_options]
testpaths = [ "tests"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64", "win-64"]

[tool.pixi.pypi-dependencies]
dlem = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.feature.dev]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]

[tool.pixi.feature.dev.dependencies]
hictk = ">=2.2.0,<3"
