[metadata]
name = dlem
version = 0.1.0
description = Tool to build, train, and use the differentiable Loop Extrusion Model (dLEM)
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE
project_urls =
    Documentation = https://chikinalab.github.io/dLEM
    Source = https://github.com/chikinalab/dLEM

[options]
packages = find:
python_requires = >=3.10,<3.13
install_requires =
    cooler
    cython>=3.2.1
    hictkpy[all]>=1.4.0
    jax>=0.4.30
    jaxlib>=0.6.2
    matplotlib>=3.10.7
    numpy
    optax>=0.2.6
    pandas>=2.3.3
    plotly>=6.3.1
    polars>=1.35.2
    pyarrow>=22.0.0
    pybigwig>=0.3.24
    pyranges>=0.1.4
    pyrle>=0.0.42
    pytest>=8.4.2
    requests>=2.32.5
    rich>=13.0.0
    scipy
    typer>=0.19.2

[options.entry_points]
console_scripts =
    dlem = dlem.cli:dlem_cli
