name: Publish Python Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "REPO_DIR=${{ vars.REPO_DIR }}" > .env
          echo "IN_DATA_DIR=${{ vars.IN_DATA_DIR }}" >> .env
          ls -la 
        shell: bash

      - name: Build the Image and Create Distributions
        run: |
          docker compose build dlem-build
          docker compose up dlem-build
          ls -la

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/ # https://upload.pypi.org/legacy/
          packages-dir: ${{ vars.REPO_DIR }}/dist
    